### PR TITLE
add tshark to param finder

### PR DESCRIPTION
**Pull request by Spitigala**

### CODE REVIEW

**Comment by JasonLunn** [comment]
👍 
Do you know the process for rebuilding and updating the plugin?

**Comment by Spitigala** [comment]
@JasonLunn Not exactly sure. Is it a matter of using 7zip and updating the jar file, as directed in the readme?

**Comment by JasonLunn** [comment]
I'll walk you through it during our 1:1

**Comment by Spitigala** [comment]
sounds good. Thanks!

**Pull request merged**
