### PR TITLE
Defensive jsp

### PR DESCRIPTION
**Pull request by JasonLunn**
Also drops support for ancient IE

### CODE REVIEW

**Comment by dthtvwls** [comment]
What do you think about this approach https://github.com/JunGroupProductions/Teamcity-Parameter-Plugin/blob/js_defensive_jsp/parameterFinder-server/src/main/resources/buildServerResources/Hello.jsp

**Comment by JasonLunn** [comment]
Either way works for me - in this case I'm not particularly concerned if unexpected elements find their way into the XML. Is it more standards compliant to make the BR tags self closing?

**Comment by dthtvwls** [comment]
[It is not](https://www.w3.org/TR/html5/syntax.html#syntax-start-tag). There were a number of other outdated/incorrect things that I cleaned up.

**Comment by dragon788** [comment]
Glad to see you guys are continuing working on this plugin. I was very excited to find it since we have a number of tools that definitely don't each need their own plugin to pull out the versions and store as agent metadata.

**Pull request merged**
